### ISSUE TITLE
BSkyblock Compatibility

### ISSUE THREAD

**Issue by BiGUNMAN** [FrankHeijden/Insights#15]
Would you consider adding bskyblock compatibility, where grouped limits for entities and blocks could be set per island and per world?
https://github.com/BentoBoxWorld

**Comment by FrankHeijden** [comment]
Hi! Thank you for reaching out :)

I also thought the same for WorldGuard regions and GriefPrevention claims, but this would really be too expensive to compute each time a player places down blocks. Insights would need to scan the whole island (which can have a very large amount of chunks, same for WG regions/claims) on each block placement, but this is just not worth it for the server and for the players. I'd also need to cancel these block placement events somehow, and if the scanning takes more than a second to compute, placing blocks one by one per second is just not gonna handle it.

I hope I could clarify it a bit, let me know if you have any more questions!

**Comment by Luky584** [comment]
Hey, for BSkyBlock try this one ;)

https://github.com/BentoBoxWorld/Limits

**Comment by FrankHeijden** [comment]
What happens for BentoBox indeed is that they cache the amount of blocks on the island, and just add blocks to this cached amount. Insights could do something similar, but this might not work nicely with other plugins which modify blocks in the chunk / region / island. For example if a player changes blocks with WorldEdit, this won't be taken into account for the limit.

**Comment by BiGUNMAN** [comment]
@Luky584 Yeah, bSkyblock (BentoBox) has something that "works", but it is not nearly as impressive or capable as Insights is. 

@FrankHeijden That makes sense, it would be really interesting to see that work for WG or GP regions, but scanning every time would not appear to be a realistic solution. Caching does sound promising but imperfect.

**Comment by FrankHeijden** [comment]
I can try adding the caching, because it may be worth it to use the caching in certain cases (for example if you don't allow players to use WorldEdit, or don't have plugins which set blocks in the world)

I will add the issue as enhancement for now - but cannot yet promise when I will implement the feature.

**Comment by BiGUNMAN** [comment]
Great! We'll gladly donate if you succeed in implementing this. We like
Insights a lot and are happy to see all the new updates :)

**Comment by FrankHeijden** [comment]
Hi, just as a follow-up question: in this particular bSkyBlock case, should Insights take care of the Protected zone, or the whole island area? (seems quite significant: by default the area of one island is 800x800 ~2601 chunks and protected zone is only 100x100 blocks  ~64 chunks)

**Comment by BiGUNMAN** [comment]
Protected zone (although this should be noted in the config comments for
users). The protection zone can be smaller, larger, and also increase over
time. (Some people might even decrease the zone).

**Comment by FrankHeijden** [comment]
Just released [v5.0.0](https://www.spigotmc.org/resources/56489/) with an addon for [BentoBox](https://www.spigotmc.org/resources/78531/) :)
