### ISSUE TITLE
selfbot

### ISSUE THREAD

**Issue by Ido156** [FrankHeijden/Insights#6]
did u manage to fix that selfbot issue? i have the same issue, please help.

**Comment by Ido156** [comment]
appu1232's selfbot

**Comment by FrankHeijden** [comment]
Hi, im sorry, I did not unfortunately.

**Comment by FrankHeijden** [comment]
I just uninstalled, ill try maybe later again. I also stopped looking for a selfbot because its kinda illegal (against the terms of Discord)
